name: CI

on: [push]

jobs:
  build-test:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6
        with:
          php_version: "8.2"

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          php_version: "8.2"
          coverage: "xdebug3"
          run: "vendor/bin/phpunit --coverage-clover=coverage.xml"
          bootstrap: "vendor/autoload.php"
